# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4154103e9b17b37e262491f182259f8414779158851cf6417174e4246c449929a11a326447e1380db59404bf482397273f9d613d4fb0ef7314857f970b79ac34

test:
  secret_key_base: db9a8df2c955e7fc4f00408289835354c72bdd3bfefc3d1cc978b7027472844333b473e2233bde3b219252853bd31abbe8f982242d1d4ddd6604b0c100cd73e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
